### ISSUE TITLE
Set up draft release notes

### ISSUE THREAD

**Issue by reshamas** [CodeYourFuture/common-theme#2]
Expansion of https://github.com/CodeYourFuture/curriculum/issues/1177 but in the relevant repo. 

- [x] Set up release.yml template for automatic release notes. https://github.com/CodeYourFuture/common-theme/pull/4
- [x] Set up RELEASE_NOTES.md file with documentation on releasing versions. https://github.com/CodeYourFuture/common-theme/pull/8

**Comment by daslerr** [comment]
@SallyMcGrath @illicitonion As per email, we shared a HackMD with you with some questions and proposed label changes, here: https://hackmd.io/@reshamas/Hky9ihibJx I can also move all that over to GitHub, if that's easier.

**Comment by illicitonion** [comment]
Thanks! This generally looks good so far!

I think a discussion about breaking changes would be useful - I happened to have recently made a change that may be a useful case study for discussion in https://github.com/CodeYourFuture/curriculum/pull/1187 - there are a few ways I could've approached this from a backwards compatibility / breaking change perspective, and some of the choices are a bit subtle. I've left comments on that PR raising them - let's maybe discuss them there?

**Comment by daslerr** [comment]
Reshama and Sally made the release.yml file in their meeting (see https://github.com/CodeYourFuture/common-theme/pull/4) and Reshama wrote up a nice checklist in release_notes.md in https://github.com/CodeYourFuture/common-theme/pull/8, so I think we're good.
